version: '3.8'

services:
  db:
    image: postgres
    container_name: postgre_db
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres123
    - POSTGRES_DB=postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    env_file: .env
    command: 
          sh -c "python manage.py makemigrations &&
                 python manage.py migrate &&
                 python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres_data: