# Generated by Django 5.2.3 on 2025-07-01 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portador',
            fields=[
                ('nome_completo', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.FloatField()),
                ('numero', models.IntegerField()),
                ('agencia', models.IntegerField()),
                ('ativa', models.BooleanField(default=False)),
                ('bloqueada', models.BooleanField(default=False)),
                ('portador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_digital', to='api.portador')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('tipo_transacao', models.CharField(choices=[('saque', 'Saque'), ('deposito', 'Deposito')])),
                ('conta_digital', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transacao', to='api.contadigital')),
            ],
        ),
    ]
