# Generated by Django 5.2.3 on 2025-07-01 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='conta_digital',
        ),
        migrations.RenameField(
            model_name='portador',
            old_name='nome_completo',
            new_name='full_name',
        ),
        migrations.CreateModel(
            name='DigitalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.FloatField()),
                ('number', models.IntegerField()),
                ('agency', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('blocked', models.BooleanField(default=True)),
                ('portador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='conta_digital', to='api.portador')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('transaction_type', models.CharField(choices=[('withdraw', 'Withdraw'), ('deposit', 'Deposit')])),
                ('created_at', models.DateField(auto_now_add=True)),
                ('digital_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='api.digitalaccount')),
            ],
        ),
        migrations.DeleteModel(
            name='ContaDigital',
        ),
        migrations.DeleteModel(
            name='Transacao',
        ),
    ]
