# Generated by Django 5.2.3 on 2025-07-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_transacao_conta_digital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalaccount',
            name='portador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='digital_account', to='api.portador'),
        ),
    ]
