# Generated by Django 5.2.3 on 2025-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_digitalaccount_portador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalaccount',
            name='current_balance',
            field=models.FloatField(default=0),
        ),
    ]
