# Generated by Django 5.2.3 on 2025-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_digitalaccount_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalaccount',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
