# Generated by Django 5.2.3 on 2025-07-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_digitalaccount_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='digitalaccount',
            constraint=models.UniqueConstraint(fields=('number', 'agency'), name='unique_number_agency'),
        ),
    ]
