# Generated by Django 5.2.3 on 2025-07-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_digitalaccount_unique_number_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalaccount',
            name='portador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='digital_account', to='api.portador'),
        ),
    ]
