# Generated by Django 5.2.3 on 2025-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_digitalaccount_portador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
